apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-eks
  labels:
    app: express-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-eks
  template:
    metadata:
      labels:
        app: express-eks
    spec:
      containers:
      - name: express-eks
        image: IMAGE_PLACEHOLDER # Placeholder to be replaced dynamically
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          value: "World"

---

apiVersion: v1
kind: Service
metadata:
  name: express-eks-service
spec:
  type: LoadBalancer
  selector:
    app: express-eks
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
