apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-eks
  labels:
    app: express-eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-eks
  template:
    metadata:
      labels:
        app: express-eks
    spec:
      containers:
      - name: express-eks
        image: 688790828242.dkr.ecr.ap-southeast-2.amazonaws.com/express-eks:latest
        ports:
        - containerPort: 3000
        env:
        - name: NAME
          value: "World"
