apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # NGINX image from Docker Hub
        ports:
        - containerPort: 80  # Default port for NGINX
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: LoadBalancer  # Exposes the service via a public IP (useful for testing)
  ports:
  - port: 80  # External port
    targetPort: 80  # Port inside the container
  selector:
    app: nginx
