name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure kubectl for EKS
      - name: Configure kubectl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}

      # Step 3: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.IMAGE_TAG }}|g" deployment.yaml
          kubectl apply -f deployment.yaml

      # Step 4: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment express-eks
