name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download Artifact from CI Workflow
      - name: Download Image Tag Artifact
        uses: actions/download-artifact@v3
        with:
          name: image-tag

      # Step 2: Read Image Tag
      - name: Read Image Tag
        id: read-tag
        run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV

      # Step 3: Configure kubectl for EKS
      - name: Configure kubectl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.CLUSTER_NAME }}

      # Step 4: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          sed -i "s|IMAGE_PLACEHOLDER|${{ env.IMAGE_TAG }}|g" deployment.yaml
          kubectl apply -f deployment.yaml

      # Step 5: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment express-eks
